# Generated by Django 2.0.5 on 2018-05-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionale', '0003_auto_20180505_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandatosepa',
            name='codicefiscalesottoscrittore',
            field=models.CharField(max_length=16, null=True, verbose_name='Codice Fiscale'),
        ),
        migrations.AlterField(
            model_name='mandatosepa',
            name='cognomesottoscrittore',
            field=models.CharField(max_length=20, null=True, verbose_name='Cognome sottoscrittore'),
        ),
        migrations.AlterField(
            model_name='mandatosepa',
            name='nomesottoscrittore',
            field=models.CharField(max_length=20, null=True, verbose_name='Nome sottoscrittore'),
        ),
    ]
